---
- name: Installing dex and Gangway setup
  hosts: dex_p2
  become: true
  #pre_tasks:
  #  - name: Includin the variables
  #    vars: 
  #      - py_ver: py2
#    - name: Ensure Pip is installed
#      package:
#        name: python-pip
#        state: present

   # - name: Ensure OpenShift client is installed.
   #   pip:
   #     name: openshift
   #     state: present
  roles:
    - role: dashboard ##gangway  ##ingress ##dex
      vars: 
        py_ver2: py2
        ansible_python_interpreter: "/usr/bin/python"


- name: Running for Python3
  hosts: dex_p2
  become: true
  roles: 
    - role: dashboard  ##gangway ##dex
      vars: 
        py_ver3: py3
        ansible_python_interpreter: "/usr/bin/python3"
